new

diff --git a/JenkinsFile b/JenkinsFile
--- a/JenkinsFile
+++ b/JenkinsFile
@@ -18,20 +18,21 @@ pipeline {
                     # List the contents of the directory
                     ls -l
 
-                    cd ./juvarya || { echo "Directory not found!"; exit 1; }
-                    
-                    # Pull the latest code from the main branch
-                    git pull origin main
-                    
-                    # Run the deployment script if it exists
-                    if [ -f ./deploy.sh ]; then
-                        ./deploy.sh
-                    else
-                        echo "deploy.sh not found!"
-                        exit 1
-                    fi
                     EOF
                     '''
+                    // cd ./juvarya || { echo "Directory not found!"; exit 1; }
+                    
+                    // # Pull the latest code from the main branch
+                    // git pull origin main
+                    
+                    // # Run the deployment script if it exists
+                    // if [ -f ./deploy.sh ]; then
+                    //     ./deploy.sh
+                    // else
+                    //     echo "deploy.sh not found!"
+                    //     exit 1
+                    // fi
+                    
                 }
             }
         }
